# This workflow builds and tests a Swift project using Swift Package Manager (SPM)
name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
    - name: Build project
      run: xcodebuild build -scheme DeeplinkRouter -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5'
    - name: Run tests with coverage
      run: xcodebuild test -scheme DeeplinkRouter -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5' -enableCodeCoverage YES
    - name: Upload coverage data
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: .build/debug/codecov.json
